#!/bin/bash
# This hook is run after every virtualenv is activated.

source <(pip completion --zsh)
[[ -f ".venv" ]] && source ".venv"

if declare -f maybe-tmux-rename-window > /dev/null
then
    maybe-tmux-rename-window $(basename ${VIRTUAL_ENV})
fi
