#!/bin/bash
# This hook is run after every virtualenv is activated.

source <(pip completion --zsh)

if [[ $VIRTUAL_ENV == "/home/lbolla/.virtualenvs/bix_model" ]]; then
    export LAUNCH_DB=1
fi;

if [[ $VIRTUAL_ENV == "/home/lbolla/.virtualenvs/bix2_ui" ]]; then
    export LAUNCH_DB=1
fi;
