#!/bin/bash
# This hook is run after every virtualenv is activated.

proj_basedir=$HOME/work
proj_name=$(echo $VIRTUAL_ENV|awk -F'/' '{print $NF}')

if [ -d "$proj_basedir/$proj_name" ]; then
        proj_dir=$proj_basedir/$proj_name
        alias cdp="cd $proj_dir"
else
        unset proj_dir
        unalias cdp
fi
